version: 2.1

jobs:
  race-check-service:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - run:
          name: "Test Service"
          command: |
            go mod vendor
            go test -race ./...
  
  benchmark-service:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - run:
          name: "Test Service"
          command: |
            go mod vendor
            go test -bench=. ./...
  
  test-service:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - run:
          name: "Test Service"
          command: |
            go mod vendor
            go test ./... -v

  code-coverage:
    docker:
      - image: cimg/go:1.19.3
    steps:
      - checkout
      - run:
          name: Run tests and collect coverage
          command: go test -race -coverprofile=coverage.txt -covermode=atomic

workflows:
  main:
    jobs:
      - test-service
      - race-check-service
      - benchmark-service
      - code-coverage

# VS Code Extension Version: 1.0.1