version: 2.1

orbs: 
  go: circleci/go@1.7.1
  golangci-lint: timakin/golangci-lint@0.1.1
  docker: circleci/docker@2.1.4
  codecov: codecov/codecov@3

jobs:
  race-check-service:
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - go/install
      - run:
          name: "Test Service"
          command: |
            go mod vendor
            go test -race ./...
  
  benchmark-service:
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - go/install
      - run:
          name: "Test Service"
          command: |
            go mod vendor
            go test -bench=. ./...
  
  test-service:
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - go/install
      - run:
          name: "Test Service"
          command: |
            go mod vendor
            go test ./... -v

  lint-service:
    docker: 
      - image: golangci/golangci-lint
    steps:
      - checkout
      - golangci-lint/lint:
          version: 1.50.1

  code-coverage:
    docker:
      - image: cimg/go:1.19.1
    steps:
      - checkout
      - run:
          name: Run tests and collect coverage
          command: go test -race -coverprofile=coverage.txt -covermode=atomic
      - codecov/upload

workflows:
  main:
    jobs:
      - test-service
      - lint-service
      - race-check-service
      - benchmark-service
      - code-coverage

# VS Code Extension Version: 1.0.1